service: ae-data-platform

useDotenv: true

provider:
  name: scaleway

  # Runtime used for functions (unless overridden)
  # List: https://www.scaleway.com/en/docs/serverless/functions/reference-content/functions-lifecycle/#available-runtimes
  runtime: python310

  minScale: 0
  maxScale: 1

  # Scaleway region for the deploy
  scwRegion: fr-par

  # Scaleway organization ID
  scwProject: ${env:SCW_PROJECT_ID}
  scwToken: ${env:SCW_TOKEN}

custom:
  functionsBasePath: src

# Include/exclude directories
package:
  patterns:
    - "!node_modules/**"
    - "!.gitignore"
    - "!.git/**"

functions:
  demo:
    handler: demo.run

plugins:
  - serverless-scaleway-functions
  - serverless-functions-base-path